### ISSUE TITLE
Significance of % in summary

### ISSUE THREAD

**Issue by e0lithic** [roskakori/pygount#103]
Hi,

If I have the following summary :
![image](https://user-images.githubusercontent.com/11680315/217973449-092fbd80-e4d9-4d43-ae9b-fb79fdc096eb.png)

What exactly does the % signify ? I was confused since they don't add up to 100% hence must be reflective of something else.

Thanks

**Comment by mathben** [comment]
I guess you have 19.2% of empty line. It's not necessary to count the empty line.
I guess you have in total 18 328 lines. So : 10 440 python lines / 18 328 total lines = 56.96% = 57.0%

**Comment by roskakori** [comment]
@mathben 
> I guess you have 19.2% of empty line.

Correct. The summary does not show empty lines because of space considerations.

Also, pygount considers some lines empty that other tools do not. For details, see [How pygount counts code](https://pygount.readthedocs.io/en/latest/background.html#how-pygount-counts-code).

You can use `--format=json` to get the number of empty lines. See [JSON](https://pygount.readthedocs.io/en/latest/json.html) and `emptyCount`.

I'm not really happy with this terse summary, but then, personally I never cared for anything but the "Code" column. The rest is just there because other tools provide this information too, and might might pester me about it if pygount didn't have it. 😉
