### ISSUE TITLE
Problems with --folders-to-skip

### ISSUE THREAD

**Issue by vagaba** [roskakori/pygount#17]
Hello!

I have tried to make the "folders-to-skip" but so far without a success. No matter how I set the pattern, all the sub-folders were scanned and added to the report.

I for example added now sub-folder "__Foo" and added some python files in it. Then I added the following example pattern from the documentation 

--folders-to-skip=[...],__*

and started the scan. All the files in "__Foo" folder were on the report. So is there a bug or am I doing something wrong? 

I am using Windows 10.

**Comment by IvanAnishchuk** [comment]
Same issue here, doesn't seem like `folders-to-skip` works at all.

**Comment by IvanAnishchuk** [comment]
I suspect it happens because [here](https://github.com/roskakori/pygount/blob/c2c150a534ba5be498eb39cb78fc6a531d62f145/pygount/analysis.py#L132-L133) `SourceScanner` is initialized with default values completely ignoring those CLI arguments. There are also some of duplicated setters/getters in `Command` and `SourceScanner` so I'm not sure how to fix it correctly without some accidental double regexp conversion.

I tried to fix it on my own but for some reason with my fixed code double conversion happens with default patters so `__pycache__` and other stuff starts appearing in the result whenever I try to add any new patterns. I'll give it another try when I have a couple free hours, this doesn't seem impossible to fix, it just needs a little more systematic approach.

**Comment by roskakori** [comment]
Yes, it seems broken. Might be able to take a look at it during the week end.

**Comment by EmilStenstrom** [comment]
I just wanted to note that I too stumbled over this problem. I have a project where I wanted to count the number of python files, but exclude all the tests in the count. `pygount -F tests` seems to include the tests directory as the library works right now.

Thanks for a great little helper script!

**Comment by pclausen** [comment]
Fix proposed in #25

**Comment by roskakori** [comment]
@pclausen Thanks for the fix! It's included into Pygount 1.1.0, which is available form pypi.
