### ISSUE TITLE
List for exceptions in the plain_text regex

### ISSUE THREAD

**Issue by nkr0** [roskakori/pygount#53]
Files like `CMakeLists.txt` fall into `pygount`'s plain_text reg-ex check, gets classified as `Text`, and counted as comment. We could modify the part [here](https://github.com/roskakori/pygount/blob/43137b40b4030c09cf64bb2a8da9efd50adcebab/pygount/analysis.py#L122) as,
```python
_STANDARD_PLAIN_TEXT_EXCEPTIONS = (
    "CMakeLists.txt",
)
_PLAIN_TEXT_PATTERN = "(?=(^" + "$)|(^".join(_STANDARD_PLAIN_TEXT_NAMES) + "$))" + "(?=(?!(^" + "$)|(^".join(_STANDARD_PLAIN_TEXT_EXCEPTIONS) + "$)))"
```
and fix this.

P.S. although this will make `CMakeLists.txt` count as code, it'll still get listed as `Text Only`. But that is a [bug in pygments/guess_lexer_for_filename](https://github.com/pygments/pygments/issues/523).

**Comment by roskakori** [comment]
Hm, after looking at my code I'm not quite sure what it is trying to achieve. IIRC the `_PLAIN_TEXT_PATTERN` was introduced to detect standard text files without any suffix (e.g. "LICENSE") as such.

At the moment essentially the following logic is used:

1. Does the filename match  `_PLAIN_TEXT_PATTERN`? -> Text
1. Does pygments have a lexer for the filename and code -> use pygments lexer
1. Does suffix of the filename match _SUFFIX_TO_FALLBACK_LEXER_MAP -> use a fallback lexer
1. Otherwise consider the file to be "__unknown__".
What makes it detect "CMakeList.txt" as text is that it also contains the regex  `".*\\.txt"`. As this is done before pygments even can take a look at, there is no way for a pygments lexer to decide that a certain file is actually code.

Having "*.txt" in `_PLAIN_TEXT_PATTERN` by now seems a bit too enthusiastic to me because this causes the exact issue you are describing. Moving it to `_SUFFIX_TO_FALLBACK_LEXER_MAP` should ensure that "*.txt" is treated as text only if pygments did not find anything else for it yet.

**Comment by roskakori** [comment]
For the record: pygements CMake lexer cannot guess many files by header due to multiple issues. I submitted a patch for that: https://github.com/pygments/pygments/pull/1491

**Comment by roskakori** [comment]
@nkr0 Pygount v1.2.3 is available on Pypi and detects `CMakelists.txt` provided the header conforms to the pygments' broken regex, which most current CMakelists.txt won't (e.g. can only detect single digit revisions numbers like 2.6 but not 3.13). 

For the full detection you will have to wait for a pygments release with the fixed regex applied. 😑

**Comment by nkr0** [comment]
Thanks for working on this. I see that your PR is still open. I'll wait for a pygments release.
