### ISSUE TITLE
Not able to calculate LOC for .vue files.  Its been categorized as "__unknown__".

### ISSUE THREAD

**Issue by jerine-ns** [roskakori/pygount#72]

**Comment by roskakori** [comment]
That's because the pygments library does not come with a vue lexer.

There seems to be the external [vue-lexer(https://github.com/testdrivenio/vue-lexer)]. As pygount currently does not support the integration of external lexers by means of configuration, you need to either modify pygount to use this, or add the lexer to pygments.

**Comment by jerine-ns** [comment]
@roskakori Thanks for the response.
