### ISSUE TITLE
Add rich formatting

### ISSUE THREAD

**Issue by Ovsyanka83** [roskakori/pygount#73]
I like this project as a python alternative to cloc but I found the output a lot less readable. So I propose an alternative SummaryWriter that uses [rich](https://github.com/willmcgugan/rich) and their table feature. I also propose to use the progress bar feature from rich because it feels uncomfortable to wait without knowing how much analysis has already been done. The progress bar will give users at least a rough estimate of how much longer to wait.

Here's what the output of RichWriter looks like:
![image](https://user-images.githubusercontent.com/17561586/147875316-d0e0d174-6b80-4e25-abff-bc8f03704a49.png)

Here's what the progressbar looks like (from rich docs):
![progress](https://github.com/willmcgugan/rich/raw/master/imgs/progress.gif)

Here's the associated pull request:
#74

**Comment by roskakori** [comment]
I'm not much invested in the standard summary format so we might as well change summary to the rich style. If people want something easy to parse, `cloc-xml` is there (and maybe eventually some JSON variant).

The progress bar makes sense but there are some consideration to end up in a Windows Explorereque crapshot:
- The basis should be the file size not the number of files.
- I'm ok with just updating the progress after each file and not after each token. This might cause the progress to stop for a while on huge files (typically generated ones) but those are bad style anyway and I have no pity for people suffering from bad style. 😉 I'd also imagine that updating the progress after each token would have a significant performance impact considering Python function calls are rather expensive compared to many other languages.
- During the initial scanning part there won't be a progress bar because it is hard to know how many files are there before finishing the scanning.
- We need a test case for 0 files and 1 file with size 0 to handle the "division by zero" scenarios.
- There will still be some uncertainty in the progress because some Pygments lexers are faster than others. Not much we can do about it though.

**Comment by roskakori** [comment]
Just noticed: For easier reading, the number columns should align to the right.

**Comment by Ovsyanka83** [comment]
Added the right justification and replaced summary with rich. 

Now, addressing some of the issues you've mentioned:
- I believe that doing it using file size is a bit of a stretch goal right now as it might require a lot more logic. And, as you have mentioned, it will make pygount significantly slower.
- The initial scanning part is incredibly fast so that's not an issue. At least that's the fastest part of the process.
- 0 files case is handled by rich so we don't need to worry about that
- The progress is mostly there so that the user doesn't have to sit and wonder whether the parsing has just started or is finishing. Accurate progress bars are always hard to implement :)

**Comment by roskakori** [comment]
>     * 0 files case is handled by rich so we don't need to worry about that

I mostly worried about the percentage column. If you have a project with a single file that is empty, the computation of the language percentage results in a "division by zero."

The current solution seems to be removing the percentage columns, which works but removes a feature.

As computing the percentage is used by multiple writers, I might as well add it to the `Summary` class, where it could handle the division by zero cases.

>     * The progress is mostly there so that the user doesn't have to sit and wonder whether the parsing has just started or is finishing. Accurate progress bars are always hard to implement :)

The heresy! ;)

Well, I guess I will look into a file size based progress.

**Comment by roskakori** [comment]
Merged.

Note to self for testing:

- Move `import contextlib` below copyright comment.
- This might not work when rich uses a fallback for plain ASCII terminals and uses a plain vertical bar (`|`) as separator. Need to test.
  ```python
  sum_total_data = [word.strip() for word in lines[-2].split("│") if word]
  ```

**Comment by roskakori** [comment]
@Ovsyanka83 pygount 1.4 has finally released 🎉 

I did a few minor changes in the visual design of the summary to better match the previous text based one (e.g. percentage columns are back).

Also a heads-up: Python 3.6 will probably be dropped with pygount 1.5 because it's causing increasing headache to keep alive. Current version of dev packages like pytest don't support it anymore, and I don't want to cling to the old versions forever.
